# Generated by Django 2.2.8 on 2019-12-27 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('cat_description', models.TextField()),
                ('cat_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp_name', models.CharField(max_length=200)),
                ('imp_description', models.TextField()),
                ('imp_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta_name', models.CharField(max_length=200)),
                ('sta_description', models.TextField()),
                ('sta_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duedate', models.DateTimeField(blank=True, null=True)),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('finishdate', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Category')),
                ('importance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Importance')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tasks',
            constraint=models.CheckConstraint(check=models.Q(startdate__lt=django.db.models.expressions.F('finishdate')), name='startdate_lt_finishdate'),
        ),
    ]
