# Generated by Django 2.2.8 on 2020-01-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='importance',
            name='imp_order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='sta_order',
            field=models.PositiveIntegerField(),
        ),
    ]
