# Generated by Django 2.2.8 on 2020-01-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200118_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='category',
            new_name='tsk_category',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='description',
            new_name='tsk_description',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='duedate',
            new_name='tsk_due_date',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='importance',
            new_name='tsk_importance',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='name',
            new_name='tsk_name',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='status',
            new_name='tsk_status',
        ),
    ]
