# Generated by Django 2.2.8 on 2020-01-29 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200118_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['cat_order']},
        ),
        migrations.AlterModelOptions(
            name='importance',
            options={'ordering': ['imp_order']},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['sta_order']},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['tsk_due_date']},
        ),
    ]
