# Generated by Django 2.2.8 on 2020-01-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200129_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='tsk_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
