# Generated by Django 2.2.8 on 2020-01-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200129_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='tsk_due_date',
            field=models.DateTimeField(),
        ),
    ]
