# Generated by Django 2.2.8 on 2020-01-29 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200129_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='tsk_importance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.Importance'),
        ),
    ]
