# Generated by Django 2.2.8 on 2020-01-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20200129_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='finishdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tsk_due_date',
            field=models.DateField(),
        ),
    ]
